repos:
  - repo: local
    hooks:
      - id: typstyle
        name: Typstyle
        entry: typstyle -i
        files: \.typ$
        language: system
        stages: [pre-commit]

      - id: commitizen
        name: commitizen check
        description: >
          Check whether the current commit message follows committing rules. Allow
          empty commit messages by default, because they typically indicate to Git
          that the commit should be aborted.
        entry: pixi run cz check
        args: [--allow-abort, --commit-msg-file]
        stages: [commit-msg]
        language: system

      - id: typst
        name: Typst
        entry: typst compile --root .
        files: (?<!conf)\.typ$
        language: system
        stages: [pre-commit]
